#!/bin/bash
### The line above is the shebang. The shebang is used to tell the environment that we are in, 
###the interpreter we are going to be using###

###The below line is asking the user what their favorite food is.
echo "What is your favorite food?"
###The below line is taking in the input from the user
read favFood

###The below line is printing a message including the value of the variable favFood that was
###taken from the input of the user.###
echo "Your favorite food is $favFood."
