#!/bin/bash

###Author: Tyriq Martin
###Description: This script will ask the user what their favorite food is, and print a message telling them what their favorite food is.
###Date: 2/27/2023

###Below, line 8 is asking the user what their favorite food is.
echo "What is your favorite food?"

#Below, line 11 is using the read command to take input from a user, and is storing the input inside a variable.
read favFood

#Below, line 14 is echoing a message using the variable favFood
echo "Your favorite food is $favFood."
